# Generated by Django 3.0.5 on 2023-10-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('challenges', models.TextField()),
                ('improvements', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
